files <- list.files("~/datasciencecoursera", full.names = TRUE)
data <- read.csv(files[2], header = TRUE, sep = ";", na.strings = "?")
data <- data[(data$Date == "1/2/2007"| data$Date == "2/2/2007"),]
data$Datetime <- strptime(paste(data$Date, data$Time),format="%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow = c(2,2))
with(data, plot(Datetime, Global_active_power, type = "l"))
with(data, plot(Datetime, Voltage, type = "l"))
with(data, plot(Datetime, Sub_metering_1, type = "l", ylab = "Energy Sub metering"))
with(data, points(Datetime, Sub_metering_2, col = "red", type = "l"))
with(data, points(Datetime, Sub_metering_3, col = "blue", type = "l"))
legend("topright", col = c("black", "red", "blue"), legend = c("submetering 1","submetering 2", "submetering 3") ,lty = 1)
with(data, plot(Datetime, Global_reactive_power, type = "l"))
dev.off()